UPDATE PLUGINS SET PRIO = 1 WHERE NAME = 'Frame';
UPDATE PLUGINS SET PRIO = 2 WHERE NAME = 'Login';
UPDATE PLUGINS SET PRIO = 3 WHERE NAME = 'Menu';
UPDATE PLUGINS SET PRIO = 4 WHERE NAME = 'Plugins';
UPDATE PLUGINS SET PRIO = 5 WHERE NAME = 'Users';